# NumPy

In [ ]:
pip install numpy

In [4]:
import numpy as np

#### Arreglos

In [10]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
arr=np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr=np.array([1,2,34,5,6],ndmin=3)#ndim indica cuantas dimensiones tiene el arreglo
print(arr.ndim)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[ 1  2 34  5  6]]]
[[ 1  2 34  5  6]]
[ 1  2 34  5  6]
1


In [14]:
arr=np.zeros((2,2))#crear arreglo de ceros
print(arr)

[[0. 0.]
 [0. 0.]]


In [12]:
arr=np.ones((3,3))#crear arreglo de unos
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
arr=np.random.rand(3,3)
print(arr)

[[0.23258044 0.02650216 0.63297112]
 [0.14741377 0.35295645 0.41526617]
 [0.51245662 0.92958174 0.24703241]]


#### Operaciones

In [16]:
arr1=[1,2,3]
arr2=[4,5,6]
arr3=np.add(arr1,arr2)#realiza la suma de los dos arreglos
print(arr3)

[5 7 9]


In [17]:
arr1=[1,2,3]
arr2=[4,5,6]
arr3=np.subtract(arr1,arr2)#realiza la resta de los arreglos
print(arr3)

[-3 -3 -3]


In [ ]:
arr1=[1,2,3]
arr2=[4,5,6]
arr3=np.multiply(arr1,arr2)#realiza la multiplicacion de los arreglos
print(arr3)

In [ ]:
arr1=[1,2,3]
arr2=[4,5,6]
arr3=np.divide(arr1,arr2)#realiza la division de los arreglos
print(arr3)

#### Agregacion

In [18]:
arr=[1,5,7]
media=np.mean(arr)
print(media)

4.333333333333333


In [19]:
arr=[1,5,7]
mediana=np.mean(arr)
print(mediana)

4.333333333333333


In [20]:
arr=[1,5,7]
maximo=np.max(arr)
print(maximo)

7


In [21]:
arr=[1,5,7]
minimo=np.min(arr)
print(minimo)

1


#### Indexacion

In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr[0])

In [ ]:
arr=np.array([1,2,3,4,5,6])#devuelve la ultima posicion 
print(arr[-1])

In [22]:
arr=np.array(([1,2,3],[4,5,6]))#devuelve el numero 6 que esta en el indice 1 posicion 2
print(arr[1,2])

6


#### Slincing

In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])#crea una rebanada desde el indice 1 hasta el 4-1(n-1)

In [23]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:4:2])#crea una rebanada desde el indice 1 hasta el 4-1 con saltos de 2

[2 4]


In [25]:
arr=np.array([1,2,3,4,5,6])
print(arr[::2])#crea una rebanada desde vacio a vacion de saltos de 2 en dos(:: significaria todo)

[1 3 5]


#### Tipos de datos

In [26]:
arr=np.array(["b","a"])
print(arr.dtype)#te brinda el tipo de dato

<U1


In [27]:
arr=np.array([1,2])
print(arr.dtype)#te brinda el tipo de dato

int32


In [30]:
arr=np.array([1,2,3],dtype='S')
#'i'= integer
#'b'= boleano
#'f'= flotante
#'M'= datetime
#'O'= objeto
#'S'= string

print(arr)

[b'1' b'2' b'3']


In [31]:
arr=np.array([1.1,2.1,3.1])
print("Pre",arr)
nuevo_arr=arr.astype('i')#convierte un arreglo a un tipo de dato, en este caso a entero
print("post",nuevo_arr)

Pre [1.1 2.1 3.1]
post [1 2 3]


#### Copy vs view

In [ ]:
arr=np.array([1,2,3])
x=arr.copy()#guarda una copia del arreglo
y=arr.view()#guarda una vista del arreglo en tiempo real
print("arr",arr)
print("copy",x)
print("view",y)

arr[0]=0

print("arr",arr)
print("copy",x)
print("view",y)



In [ ]:
arr=np.array([1,2,4])
print("arr",arr)
x=arr.view()
print("x view",x)


#### concatenar

In [34]:
arr1=np.array([1,2,3])
print("arr1",arr1)
arr1=np.array([4,5,6])
print("arr2",arr2)
arr3=np.concatenate((arr1,arr2))#concatena no suma dos arreglos
print("arr3",arr3)

arr1 [1 2 3]
arr2 [4, 5, 6]
arr3 [4 5 6 4 5 6]


#### concatenar

In [36]:
arr=np.array([1,2,2,4,5,4])
x=np.where(arr==5)#busca y regresa el indice donde se encuentra el elemento
print(x)

(array([4], dtype=int64),)


#### Ordenar

In [ ]:
arr=np.array([1,2,2,4,5,4])
x=np.sort(arr)#ordena un arreglo
print(x)

# Pandas

In [57]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [39]:
import pandas as pd

#### Series

In [40]:
a=np.array([1,2,3])
srs=pd.Series(a)#crea una serie a la cual se le da un indice para cada dato
print(srs)
print(srs[0])

0    1
1    2
2    3
dtype: int32
1


In [42]:
srs=pd.Series(a,index=["x","y","z"])#aqui se les da nombre a los indices
print(srs)
print(srs["x"])

x    1
y    2
z    3
dtype: int32
1


In [44]:
pasos={
    "Lunes":540,
    "Martes":620,
    "Miercoles":700,
    "Jueves":500,
    "Viernes":150

}
srs=pd.Series(pasos)#se le puede pasar un diccionario
print(srs)

Lunes        540
Martes       620
Miercoles    700
Jueves       500
Viernes      150
dtype: int64


In [47]:
srs=pd.Series(pasos,index=["Martes","Miercoles"])#se puede filtrar por indice
print(srs)

Martes       620
Miercoles    700
dtype: int64


#### DataFrame

In [48]:
myDataSet={
    "operador":["jhon doe","sr.x","lorem ipsum"],
    "no. reloj":[101,202,303]
}
df=pd.DataFrame(myDataSet)
print(df)

      operador  no. reloj
0     jhon doe        101
1         sr.x        202
2  lorem ipsum        303


In [ ]:
df['no. reloj']#trae  todos los datos de la columna

In [49]:
df[df['no. reloj']>101]#se filtra por la columna no reloj que cumplan con la condicion 

operador  no. reloj
1         sr.x        202
2  lorem ipsum        303

In [50]:
df['asistencia']=[True,False,True]#se crea una columna nueva y se le pasan esos valores

In [51]:
print(df)

      operador  no. reloj  asistencia
0     jhon doe        101        True
1         sr.x        202       False
2  lorem ipsum        303        True


In [52]:
print(df.loc[0])#trae los recursos dentro de ese indice

operador      jhon doe
no. reloj          101
asistencia        True
Name: 0, dtype: object


In [53]:
df=pd.DataFrame(myDataSet,index=["CEO","COO","CFO"])#se puede cambiar el nombre de los indices
print(df)

        operador  no. reloj
CEO     jhon doe        101
COO         sr.x        202
CFO  lorem ipsum        303


In [54]:
print(df.loc["CEO"])

operador     jhon doe
no. reloj         101
Name: CEO, dtype: object


In [56]:
print(df.loc[["CEO","COO"]])#filtrar por indices

     operador  no. reloj
CEO  jhon doe        101
COO      sr.x        202


#### Vistas

In [59]:
df=pd.read_csv("perfil de estudiante.csv")#leer los datos de un csv

In [63]:
df.head()#te trae los 5 primeros registros , se puede manipular para que traiga los registros que quieres , poniendo numero dentro de los parentesis 

Marca temporal 1.- ¿De dónde eres?  \
0  2023/06/27 7:42:12 p. m. GMT-6          Cd. Juárez   

  2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
0             Entre 21 y 24             Sí             No   

  5.- ¿Cuál es tu nivel de conocimiento en Python?  \
0                                           Básico   

  6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
0                             Manejar bases de datos           

  7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
0                                                 No                   

  8.- ¿Cuál es tu canción favorita?  
0                          The Wolf

In [65]:
df.tail()#te trae los ultimos 5 registros, se puede colocar el numero de registros dentro del parentesis

Marca temporal 1.- ¿De dónde eres?  \
42  2023/07/03 1:55:24 p. m. GMT-6       Ciudad Juarez   

   2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
42                 Más de 30             No             Sí   

   5.- ¿Cuál es tu nivel de conocimiento en Python?  \
42                                       Intermedio   

   6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
42                                     Automatizacion           

   7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
42                                                 No                   

   8.- ¿Cuál es tu canción favorita?  
42             David Bowie - Heroes

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                                                              Non-Null Count  Dtype 
---  ------                                                              --------------  ----- 
 0   Marca temporal                                                      43 non-null     object
 1   1.- ¿De dónde eres?                                                 43 non-null     object
 2   2.- ¿Cuántos años tienes?                                           43 non-null     object
 3   3.- ¿Estudias?                                                      43 non-null     object
 4   4.- ¿Trabajas?                                                      43 non-null     object
 5   5.- ¿Cuál es tu nivel de conocimiento en Python?                    43 non-null     object
 6   6.- ¿Qué tema relacionado con Python te gustaría aprender?          43 non-null     object
 7   7.- ¿Has participado en algún

#### cvs

In [67]:
df=pd.read_csv("perfil de estudiante.csv")#leer los datos de un csv
print(df.to_string())

                     Marca temporal                        1.- ¿De dónde eres? 2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas? 5.- ¿Cuál es tu nivel de conocimiento en Python?                                           6.- ¿Qué tema relacionado con Python te gustaría aprender? 7.- ¿Has participado en algún curso anteriormente en el IA Center?                             8.- ¿Cuál es tu canción favorita?
0    2023/06/27 7:42:12 p. m. GMT-6                                 Cd. Juárez             Entre 21 y 24             Sí             No                                           Básico                                                                               Manejar bases de datos                                                                 No                                                      The Wolf
1    2023/06/27 7:42:28 p. m. GMT-6                       chihuahua, chihuahua             Entre 21 y 24             Sí             Sí                                      

#### JSON

In [68]:
df=pd.read_json("dataset.json")
print(df.to_string())

                                                 personas
0      {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}
1  {'nombre': 'María', 'edad': 30, 'ciudad': 'Barcelona'}
2   {'nombre': 'Pedro', 'edad': 35, 'ciudad': 'Valencia'}


#### Limpieza de datos

In [74]:
data={
    'Nombre':['Juan','Maria','Pedro','Ana','luis'],
    'Edad':[25,32,None,42,28],
    'Fecha':['31/01/2023','31/01/2023',None,'31/01/2023','31/01/2023'],
    'Genero':['M','F',None,'M','F'],
    'Ciudad':['Madrid',None,'Madrid','Valencia','Barcelona'],
    'Altura':[175,163,180,158,170],
    'Peso':[70,None,80,60,75],
    'Ingresos':[50000,60000,40000,None,55000]
      }

In [75]:
df=pd.DataFrame(data)
print(df)

  Nombre  Edad       Fecha Genero     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2023      M     Madrid     175  70.0   50000.0
1  Maria  32.0  31/01/2023      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2023      M   Valencia     158  60.0       NaN
4   luis  28.0  31/01/2023      F  Barcelona     170  75.0   55000.0


In [76]:
df_sin_vacios=df.dropna()#recupera los registros que no tienen algun vacio
print(df_sin_vacios.to_string())

  Nombre  Edad       Fecha Genero     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2023      M     Madrid     175  70.0   50000.0
4   luis  28.0  31/01/2023      F  Barcelona     170  75.0   55000.0


In [79]:
df.dropna(inplace=True)#inplace significa que se va a hacer dentro del dataframe, en este caso se esta borrando los registros que tienen lgun vacio
print(df)

  Nombre  Edad       Fecha Genero     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2023      M     Madrid     175  70.0   50000.0
4   luis  28.0  31/01/2023      F  Barcelona     170  75.0   55000.0


In [80]:
df.fillna("Sin registros",inplace=True)#se reemplaza el registro vacio por la palabra sin registro
print(df)

  Nombre  Edad       Fecha Genero     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2023      M     Madrid     175  70.0   50000.0
4   luis  28.0  31/01/2023      F  Barcelona     170  75.0   55000.0


In [81]:
df["Ingresos"].fillna(0,inplace=True)#se reemplaza el registro vacio de la columna ingresos por 0
print(df)

  Nombre  Edad       Fecha Genero     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2023      M     Madrid     175  70.0   50000.0
4   luis  28.0  31/01/2023      F  Barcelona     170  75.0   55000.0


In [ ]:
df_cero=df["Ingresos"].fillna(0)##se reemplaza el registro vacio de la columna ingresos por 0 en un nuevo dataframe
print(df_cero)

In [ ]:
media=df["Ingresos"].mean()
print(media)